apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-conf
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: "wordpress-mysql"
  WORDPRESS_DB_USER: "your_db_user"
  WORDPRESS_DB_NAME: "your_db_name"