apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.6.2-php8.3-fpm-alpine
          ports:
            - containerPort: 9000
          env:
            - name: WORDPRESS_DB_HOST
              value: "<YOUR_DB_HOST>"
            - name: WORDPRESS_DB_USER
              value: "<YOUR_DB_USER>"
            - name: WORDPRESS_DB_PASSWORD
              value: "<YOUR_DB_PASSWORD>"
            - name: WORDPRESS_DB_NAME
              value: "<YOUR_DB_NAME>"
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-persistent-storage
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
