apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.6.2-php8.3-fpm-alpine
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html/wordpress/wp-content
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-conf
                key: WORDPRESS_DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: wordpress-conf
                key: WORDPRESS_DB_USER
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress-conf
                key: WORDPRESS_DB_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-db-mariadb-galera
                key: mariadb-root-password
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi