apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    # Main Nginx configuration
    user nginx;
    worker_processes 1;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
    }

    # The http block
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        access_log  /var/log/nginx/access.log;
        error_log   /var/log/nginx/error.log;

        # Server block
        server {
            listen 80;
            server_name example.com;

            # Document root for the site
            root /var/www/html;
            index index.php index.html;

            # Main location block
            location / {
                try_files $uri $uri/ /index.php?$args;
            }

            # PHP handler for WordPress
            location ~ \.php$ {
                include fastcgi_params;
                fastcgi_pass wordpress-service:9000; # WordPress service on port 9000
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }

            # Static file caching
            location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|ttf|woff|woff2)$ {
                expires max;
                log_not_found off;
            }
        }
    }
